config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :companies, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Company < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id         :integer          not null, primary key
#  name       :string
#  company_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_employees_on_company_id  (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#

class Employee < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @with_includes = !(params[:n_p_1] == "true")
    @companies = 

    @companies = if @with_includes
      Company.includes(:employees)
    else
      Company
    end.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @github_link = "https://github.com/flyerhzm/bullet"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.haml
%card
  .card-block
    %h3.text-center
      %u #{@with_includes ? "No Issues" : "Have N+1 Queries Issue"}
    .table-responsive
      %table.table{style: "width:100%"}
        %thead
          %tr
            %th Company
            %th.text-center No. of Employees
            %th.text-center Employee Names

        %tbody
          -@companies.each do |c|
            -employees = c.employees
            %tr
              %td=c.name
              %td.text-center=employees.size
              %td.text-center
                -if employees.size > 0
                  %ul.list-unstyled
                    -c.employees.each do |e|
                      %li=e.name
                -else
                  No Employees.

app/views/home/index.html.haml
.card
  .card-block.text-center.align-middle{style: "padding:20px;min-height:200px"}   
    %br 
    =link_to "With N+1 Issue", companies_path(n_p_1: true), class: "btn btn-primary"
    =link_to "Without N+1 Issue", companies_path(n_p_1: false), class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bullet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    :css
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    / Navigation
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      .container
        %a.navbar-brand{:href => "#"} RubyGems
        %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item.active
              %a.nav-link{:href => "#"}
                Bullet
                %span.sr-only (current)

    / Page Content
    .container
      .row
        .col-lg-4.text-center
          %h1.mt-5 Demo
        .col-lg-8
          %br
          %p.lead 
            Bullet to detect N+1 Query.
            %br
            %a{href: @github_link}=@github_link
          %ul.list-unstyled
            %li Version: v5.9.0
            %li Last Updated: 26th Mar 2019
      .row
        .col-lg-12
          =yield